Decouple MythTV configure from FFmpeg configure, first step
Instead of having MythTV configure do all the work that is needed for
FFmpeg, rather have MythTV configure invoke the FFmpeg configure.
This eliminates the need to keep updating MythTV configure with FFmpeg
changes.

This is step 1. FFmpeg configure is invoked and MythTV configure does
none of the FFmpeg work. There is still much unneeded FFmpeg
code in the MythTV configure.

Refs #13259

diff --git a/mythtv/configure b/mythtv/configure
--- a/mythtv/configure
+++ b/mythtv/configure
@@ -8396,6 +8396,85 @@ elif enabled gpl; then
     license="GPL version 2 or later"
 fi
 
+# Set up FFmpeg configure options that are derived from
+# MythTV configure options
+
+ffmpeg_optset() {
+    while test -n "$1" ; do
+        val=$(eval "echo \$$1")
+        if test -n "$val" ; then
+            ffopts="$ffopts '--$1=$(echo "$val")'"
+        fi
+        shift
+    done
+}
+
+ffmpeg_optenable() {
+    while test -n "$1" ; do
+        val=$(eval "echo \$$1")
+        if enabled "$val" ; then
+            ffopts="$ffopts --enable-"$(echo "$val" | sed 's/_/-/g')
+        fi
+        shift
+    done
+}
+
+ffopts=
+ffmpeg_optset arch cross_prefix sysroot sysinclude cc cxx ld cpu
+ffmpeg_optset extra_cxxflags extra_ldflags target_os
+ffmpeg_optset pkg_config prefix as objcc dep_cc host_cc
+ffmpeg_optset host_ld
+ffmpeg_optenable cross_compile libmp3lame libx264 libvpx libxvid
+ffmpeg_optenable sdl2 vdpau vaapi libxml2 libass dxva2 opengl
+ffmpeg_extra_cflags="$extra_cflags -w"
+
+## Call FFmpeg configure here
+currentpwd="$PWD"
+cd external/FFmpeg
+eval ./configure \
+$ffopts \
+--extra-cflags='"$ffmpeg_extra_cflags"' \
+--enable-stripping \
+--strip='"echo skipping strip"' \
+--disable-manpages  \
+--disable-podpages  \
+--disable-doc \
+--disable-nvenc \
+--enable-shared \
+--disable-static \
+--enable-gpl \
+--disable-ffplay \
+--enable-pic \
+--disable-demuxer=mpegtsraw \
+--disable-indev=dshow \
+--disable-avio_dir_cmd_example \
+--disable-avio_reading_example \
+--disable-decode_audio_example \
+--disable-decode_video_example \
+--disable-demuxing_decoding_example \
+--disable-encode_audio_example \
+--disable-encode_video_example \
+--disable-extract_mvs_example \
+--disable-filter_audio_example \
+--disable-filtering_audio_example \
+--disable-filtering_video_example \
+--disable-http_multiclient_example \
+--disable-hw_decode_example \
+--disable-metadata_example \
+--disable-muxing_example \
+--disable-qsvdec_example \
+--disable-remuxing_example \
+--disable-resampling_audio_example \
+--disable-scaling_video_example \
+--disable-transcode_aac_example \
+--disable-transcoding_example
+rc=$?
+if [ $rc != 0 ] ; then
+    echo "ERROR FFmpeg configure failed"
+    exit $rc
+fi
+cd "$currentpwd"
+
 if test "$quiet" != "yes"; then
 
 echo "# Basic Settings"
@@ -8930,12 +9009,12 @@ cat > $TMPH <<EOF
 #define QT_MIN_VERSION_STR "$QT_MIN_VERSION_STR"
 #define QT_MIN_VERSION_HEX $QT_MIN_VERSION_HEX
 #define QT_MIN_VERSION $QT_MIN_VERSION
-#define FFMPEG_CONFIGURATION "$(c_escape $FFMPEG_CONFIGURATION)"
-#define FFMPEG_LICENSE "$(c_escape $license)"
-#define CONFIG_THIS_YEAR 2017
-#define FFMPEG_DATADIR "$(eval c_escape $datadir)"
-#define AVCONV_DATADIR "$(eval c_escape $datadir)"
-#define CC_IDENT "$(c_escape ${cc_ident:-Unknown compiler})"
+// #define FFMPEG_CONFIGURATION "$(c_escape $FFMPEG_CONFIGURATION)"
+// #define FFMPEG_LICENSE "$(c_escape $license)"
+// #define CONFIG_THIS_YEAR 2017
+// #define FFMPEG_DATADIR "$(eval c_escape $datadir)"
+// #define AVCONV_DATADIR "$(eval c_escape $datadir)"
+// #define CC_IDENT "$(c_escape ${cc_ident:-Unknown compiler})"
 #define av_restrict $_restrict
 #define EXTERN_PREFIX "${extern_prefix}"
 #define EXTERN_ASM ${extern_prefix}
@@ -9164,7 +9243,8 @@ fi
 
 
 # create config.mak for external/FFmpeg
-cat >  external/FFmpeg/ffbuild/config.mak <<EOF
+#### NO MORE cat >  external/FFmpeg/ffbuild/config.mak
+<<EOF
 # Automatically generated by configure - do not modify!
 ifndef FFMPEG_CONFIG_MAK
 FFMPEG_CONFIG_MAK=1
@@ -9176,8 +9256,9 @@ SLIB_INSTALL_EXTRA_CMD=${SLIB_INSTALL_EXTRA_CMD}
 SLIB_UNINSTALL_EXTRA_CMD=${SLIB_UNINSTALL_EXTRA_CMD}
 EOF
 # Strip out the old dirs that we are about to put back in.
-sed -e '/^S?H?LIBDIR=.*$/d' -e '/^INCDIR=.*$/d' -e '/^BINDIR=.*$/d' -e '/^DATADIR=.*$/d' -e '/^MANDIR=.*$/d' $TMPMAK >> external/FFmpeg/ffbuild/config.mak
-cat >> external/FFmpeg/ffbuild/config.mak <<EOF
+#### NO MORE sed -e '/^S?H?LIBDIR=.*$/d' -e '/^INCDIR=.*$/d' -e '/^BINDIR=.*$/d' -e '/^DATADIR=.*$/d' -e '/^MANDIR=.*$/d' $TMPMAK >> external/FFmpeg/ffbuild/config.mak
+#### NO MORE cat >> external/FFmpeg/ffbuild/config.mak
+<<EOF
 LIBDIR=\$(INSTALL_ROOT)$libdir
 SHLIBDIR=\$(INSTALL_ROOT)$shlibdir
 INCDIR=\$(INSTALL_ROOT)$incdir
@@ -9189,11 +9270,11 @@ endif # FFMPEG_CONFIG_MAK
 EOF
 
 # link config.h into external/FFmpeg
-rm -f external/FFmpeg/ffbuild/config.h
-(cd external/FFmpeg/ && ${ln_s} ../../$MYTH_CONFIG_H config.h)
-touch external/FFmpeg/ffbuild/.config
+#### NO MORE rm -f external/FFmpeg/ffbuild/config.h
+#### NO MORE (cd external/FFmpeg/ && ${ln_s} ../../$MYTH_CONFIG_H config.h)
+#### NO MORE touch external/FFmpeg/ffbuild/.config
 
-enabled x86asm && cp_if_changed $TMPASM external/FFmpeg/config.asm
+#### NO MORE  enabled x86asm && cp_if_changed $TMPASM external/FFmpeg/config.asm
 
 # delete old myth config files in old location
 if [ -e libs/libmyth/mythconfig.mak ] ; then
@@ -9213,7 +9294,7 @@ print_config AV_HAVE_ $TMPH $HAVE_LIST_PUB
 
 echo "#endif /* AVUTIL_AVCONFIG_H */" >> $TMPH
 
-cp_if_changed $TMPH external/FFmpeg/libavutil/avconfig.h
+#### NO MORE cp_if_changed $TMPH external/FFmpeg/libavutil/avconfig.h
 
 <<BLOCKQUOTE
 echo "config:$arch:$subarch:$cpu:$target_os:$cc_ident:$FFMPEG_CONFIGURATION" >config.fate
@@ -9289,12 +9370,13 @@ print_enabled_components(){
     cp_if_changed $TMPH $file
 }
 
-print_enabled_components external/FFmpeg/libavcodec/bsf_list.c AVBitStreamFilter bitstream_filters $BSF_LIST
-print_enabled_components external/FFmpeg/libavformat/protocol_list.c URLProtocol url_protocols $PROTOCOL_LIST
+#### NO MORE print_enabled_components external/FFmpeg/libavcodec/bsf_list.c AVBitStreamFilter bitstream_filters $BSF_LIST
+#### NO MORE print_enabled_components external/FFmpeg/libavformat/protocol_list.c URLProtocol url_protocols $PROTOCOL_LIST
 
 # Settings for pkg-config files
 
-cat > external/FFmpeg/ffbuild/config.sh <<EOF
+#### NO MORE cat > external/FFmpeg/ffbuild/config.sh
+<<EOF
 # Automatically generated by configure - do not modify!
 shared=$shared
 build_suffix=$build_suffix
@@ -9317,9 +9399,9 @@ extralibs_swscale="$LIBM"
 extralibs_swresample="$LIBM $LIBSOXR"
 EOF
 
-for lib in $LIBRARY_LIST; do
-    lib_deps="$(eval echo \$${lib}_deps)"
-    echo ${lib}_deps=\"$lib_deps\" >> external/FFmpeg/ffbuild/config.sh
-done
+#### NO MORE for lib in $LIBRARY_LIST; do
+#### NO MORE     lib_deps="$(eval echo \$${lib}_deps)"
+#### NO MORE     echo ${lib}_deps=\"$lib_deps\" >> external/FFmpeg/ffbuild/config.sh
+#### NO MORE done
 
 test -n "$WARNINGS" && printf "\n$WARNINGS" || exit 0
